# Generated by Django 4.1.4 on 2023-03-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akhil',
            old_name='dec',
            new_name='desc',
        ),
    ]
