# Generated by Django 4.1.4 on 2023-03-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_dec_akhil_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='akhil',
            new_name='Appointments',
        ),
    ]
