# Generated by Django 4.1.4 on 2023-03-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_signinpeople'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signinpeople',
        ),
    ]
