# Generated by Django 4.1.4 on 2023-05-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_tests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signinpeople',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
