# Generated by Django 4.1.4 on 2023-05-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_delete_signinpeople_delete_tests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Cardiology',
        ),
    ]
