# Generated by Django 4.1.4 on 2023-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_bloodtest_ctscan_endoscopy_kemotheraphy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ctscan',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endoscopy',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kemotheraphy',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pulmonaryfuctiontest',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='urinetest',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='xray',
            name='age',
            field=models.IntegerField(),
        ),
    ]
